# Use the official Rust image to build your application
FROM rust:1.75 as builder

# Create a new empty shell project
RUN USER=root cargo new --bin azeroth_dock
WORKDIR /azeroth_dock

# Copy your manifests
COPY ./Cargo.toml ./Cargo.toml
COPY ./Cargo.lock ./Cargo.lock

# This trick will cache your dependencies to not rebuild them on every build
RUN cargo build --release
RUN rm src/*.rs

# Copy your source tree
COPY ./src ./src
RUN ls -la

# Copy your templates directory
COPY ./templates ./templates

# Since we are directly building the project in the next step, 
# we can omit the problematic command that was deleting dependencies.

# Build for release
RUN cargo build --release
RUN ls -la target/release/

# Use the Debian slim image for the runtime base
# This is a small and secure base image
FROM debian:bookworm-slim

# Install SSL certificates and possible SSL libraries
RUN apt-get update && apt-get install -y libssl3 ca-certificates || apt-get install -y libssl-dev ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /azeroth_dock
COPY --from=builder /azeroth_dock/target/release/azeroth_dock .
COPY --from=builder /azeroth_dock/templates ./templates

# Set Rocket to listen on all network interfaces
ENV ROCKET_ADDRESS=0.0.0.0

# This command runs your application
CMD ["./azeroth_dock"]
